import type { PokemonApiResponse } from "../types/pokemon";

export const mockPokemonCards: PokemonApiResponse = {
  data: [
    {
      id: "hgss4-1",
      name: "Aggron",
      supertype: "Pokémon",
      subtypes: ["Stage 2"],
      hp: "140",
      types: ["Metal"],
      evolvesFrom: "Lairon",
      attacks: [
        {
          name: "Second Strike",
          cost: ["Metal", "Metal", "Colorless"],
          convertedEnergyCost: 3,
          damage: "40",
          text: "If the Defending Pokémon already has any damage counters on it, this attack does 40 damage plus 40 more damage.",
        },
        {
          name: "Guard Claw",
          cost: ["Metal", "Metal", "Colorless", "Colorless"],
          convertedEnergyCost: 4,
          damage: "60",
          text: "During your opponent's next turn, any damage done to Aggron by attacks is reduced by 20 (after applying Weakness and Resistance).",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      resistances: [
        {
          type: "Psychic",
          value: "-20",
        },
      ],
      retreatCost: ["Colorless", "Colorless", "Colorless", "Colorless"],
      convertedRetreatCost: 4,
      set: {
        id: "hgss4",
        name: "HS—Triumphant",
        series: "HeartGold & SoulSilver",
        printedTotal: 102,
        total: 103,
        legalities: {
          unlimited: "Legal",
        },
        ptcgoCode: "TM",
        releaseDate: "2010/11/03",
        updatedAt: "2018/03/04 10:35:00",
        images: {
          symbol: "https://images.pokemontcg.io/hgss4/symbol.png",
          logo: "https://images.pokemontcg.io/hgss4/logo.png",
        },
      },
      number: "1",
      artist: "Kagemaru Himeno",
      rarity: "Rare Holo",
      flavorText:
        "You can tell its age by the length of its iron horns. It claims an entire mountain as its territory.",
      nationalPokedexNumbers: [306],
      legalities: {
        unlimited: "Legal",
      },
      images: {
        small: "https://images.pokemontcg.io/hgss4/1.png",
        large: "https://images.pokemontcg.io/hgss4/1_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/hgss4-1",
        updatedAt: "2025/08/06",
        prices: {
          holofoil: {
            low: 3.49,
            mid: 4.39,
            high: 17.5,
            market: 2.61,
            directLow: 4.39,
          },
          reverseHolofoil: {
            low: 2.0,
            mid: 2.0,
            high: 2.0,
            market: 3.17,
            directLow: null,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/hgss4-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 2.12,
          lowPrice: 0.3,
          trendPrice: 3.87,
          germanProLow: 0.0,
          suggestedPrice: 0.0,
          reverseHoloSell: 0.97,
          reverseHoloLow: 0.85,
          reverseHoloTrend: 3.25,
          lowPriceExPlus: 1.0,
          avg1: 10.0,
          avg7: 3.69,
          avg30: 2.67,
          reverseHoloAvg1: 0.97,
          reverseHoloAvg7: 3.27,
          reverseHoloAvg30: 3.65,
        },
      },
    },
    {
      id: "xy5-1",
      name: "Weedle",
      supertype: "Pokémon",
      subtypes: ["Basic"],
      hp: "50",
      types: ["Grass"],
      evolvesTo: ["Kakuna"],
      attacks: [
        {
          name: "Multiply",
          cost: ["Grass"],
          convertedEnergyCost: 1,
          damage: "",
          text: "Search your deck for Weedle and put it onto your Bench. Shuffle your deck afterward.",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless"],
      convertedRetreatCost: 1,
      set: {
        id: "xy5",
        name: "Primal Clash",
        series: "XY",
        printedTotal: 160,
        total: 164,
        legalities: {
          unlimited: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "PRC",
        releaseDate: "2015/02/04",
        updatedAt: "2020/05/01 16:06:00",
        images: {
          symbol: "https://images.pokemontcg.io/xy5/symbol.png",
          logo: "https://images.pokemontcg.io/xy5/logo.png",
        },
      },
      number: "1",
      artist: "Midori Harada",
      rarity: "Common",
      flavorText:
        "Its poison stinger is very powerful. Its bright-colored body is intended to warn off its enemies.",
      nationalPokedexNumbers: [13],
      legalities: {
        unlimited: "Legal",
        expanded: "Legal",
      },
      images: {
        small: "https://images.pokemontcg.io/xy5/1.png",
        large: "https://images.pokemontcg.io/xy5/1_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/xy5-1",
        updatedAt: "2025/08/06",
        prices: {
          normal: {
            low: 0.03,
            mid: 0.18,
            high: 4.95,
            market: 0.14,
            directLow: null,
          },
          reverseHolofoil: {
            low: 0.19,
            mid: 0.47,
            high: 4.95,
            market: 0.69,
            directLow: 0.19,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/xy5-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 0.09,
          lowPrice: 0.02,
          trendPrice: 0.18,
          germanProLow: 0.0,
          suggestedPrice: 0.0,
          reverseHoloSell: 0.82,
          reverseHoloLow: 0.15,
          reverseHoloTrend: 0.51,
          lowPriceExPlus: 0.02,
          avg1: 0.15,
          avg7: 0.13,
          avg30: 0.11,
          reverseHoloAvg1: 0.5,
          reverseHoloAvg7: 0.57,
          reverseHoloAvg30: 0.49,
        },
      },
    },
    {
      id: "pl1-1",
      name: "Ampharos",
      supertype: "Pokémon",
      subtypes: ["Stage 2"],
      level: "57",
      hp: "130",
      types: ["Lightning"],
      evolvesFrom: "Flaaffy",
      abilities: [
        {
          name: "Damage Bind",
          text: "Each Pokémon that has any damage counters on it (both yours and your opponent's) can't use any Poké-Powers.",
          type: "Poké-Body",
        },
      ],
      attacks: [
        {
          name: "Gigavolt",
          cost: ["Lightning", "Colorless"],
          convertedEnergyCost: 2,
          damage: "30+",
          text: "Flip a coin. If heads, this attack does 30 damage plus 30 more damage. If tails, the Defending Pokémon is now Paralyzed.",
        },
        {
          name: "Reflect Energy",
          cost: ["Lightning", "Colorless", "Colorless"],
          convertedEnergyCost: 3,
          damage: "70",
          text: "Move an Energy card attached to Ampharos to 1 of your Benched Pokémon.",
        },
      ],
      weaknesses: [
        {
          type: "Fighting",
          value: "+30",
        },
      ],
      resistances: [
        {
          type: "Metal",
          value: "-20",
        },
      ],
      retreatCost: ["Colorless", "Colorless"],
      convertedRetreatCost: 2,
      set: {
        id: "pl1",
        name: "Platinum",
        series: "Platinum",
        printedTotal: 127,
        total: 133,
        legalities: {
          unlimited: "Legal",
        },
        ptcgoCode: "PL",
        releaseDate: "2009/02/11",
        updatedAt: "2020/08/14 09:35:00",
        images: {
          symbol: "https://images.pokemontcg.io/pl1/symbol.png",
          logo: "https://images.pokemontcg.io/pl1/logo.png",
        },
      },
      number: "1",
      artist: "Atsuko Nishida",
      rarity: "Rare Holo",
      nationalPokedexNumbers: [181],
      legalities: {
        unlimited: "Legal",
      },
      images: {
        small: "https://images.pokemontcg.io/pl1/1.png",
        large: "https://images.pokemontcg.io/pl1/1_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/pl1-1",
        updatedAt: "2025/08/06",
        prices: {
          holofoil: {
            low: 5.39,
            mid: 9.3,
            high: 14.51,
            market: 10.44,
            directLow: null,
          },
          reverseHolofoil: {
            low: 10.0,
            mid: 13.0,
            high: 17.95,
            market: 9.18,
            directLow: null,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/pl1-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 6.21,
          lowPrice: 0.6,
          trendPrice: 5.19,
          germanProLow: 0.0,
          suggestedPrice: 0.0,
          reverseHoloSell: 5.74,
          reverseHoloLow: 1.0,
          reverseHoloTrend: 4.71,
          lowPriceExPlus: 3.45,
          avg1: 3.99,
          avg7: 5.37,
          avg30: 6.0,
          reverseHoloAvg1: 4.0,
          reverseHoloAvg7: 5.63,
          reverseHoloAvg30: 3.68,
        },
      },
    },
    {
      id: "dp3-1",
      name: "Ampharos",
      supertype: "Pokémon",
      subtypes: ["Stage 2"],
      level: "52",
      hp: "130",
      types: ["Lightning"],
      evolvesFrom: "Flaaffy",
      abilities: [
        {
          name: "Jamming",
          text: "After your opponent plays a Supporter card from his or her hand, put 1 damage counter on each of your opponent's Pokémon. You can't use more than 1 Jamming Poké-Body each turn.",
          type: "Poké-Body",
        },
      ],
      attacks: [
        {
          name: "Cluster Bolt",
          cost: ["Lightning", "Colorless", "Colorless"],
          convertedEnergyCost: 3,
          damage: "70",
          text: "You may discard all Lightning Energy attached to Ampharos. If you do, this attack does 20 damage to each of your opponent's Benched Pokémon that has any Energy cards attached to it. (Don't apply Weakness and Resistance for Benched Pokémon.)",
        },
      ],
      weaknesses: [
        {
          type: "Fighting",
          value: "+30",
        },
      ],
      resistances: [
        {
          type: "Metal",
          value: "-20",
        },
      ],
      retreatCost: ["Colorless", "Colorless", "Colorless"],
      convertedRetreatCost: 3,
      set: {
        id: "dp3",
        name: "Secret Wonders",
        series: "Diamond & Pearl",
        printedTotal: 132,
        total: 132,
        legalities: {
          unlimited: "Legal",
        },
        ptcgoCode: "SW",
        releaseDate: "2007/11/01",
        updatedAt: "2018/03/04 10:35:00",
        images: {
          symbol: "https://images.pokemontcg.io/dp3/symbol.png",
          logo: "https://images.pokemontcg.io/dp3/logo.png",
        },
      },
      number: "1",
      artist: "Kouki Saitou",
      rarity: "Rare Holo",
      flavorText:
        "The tip of its tail shines brightly. In the olden days, people sent signals using the tail's light.",
      nationalPokedexNumbers: [181],
      legalities: {
        unlimited: "Legal",
      },
      images: {
        small: "https://images.pokemontcg.io/dp3/1.png",
        large: "https://images.pokemontcg.io/dp3/1_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/dp3-1",
        updatedAt: "2025/08/06",
        prices: {
          holofoil: {
            low: 8.74,
            mid: 20.0,
            high: 62.98,
            market: 19.03,
            directLow: 8.49,
          },
          reverseHolofoil: {
            low: 7.45,
            mid: 14.95,
            high: 4321.0,
            market: 13.95,
            directLow: 16.38,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/dp3-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 2.26,
          lowPrice: 0.29,
          trendPrice: 2.62,
          germanProLow: 0.0,
          suggestedPrice: 0.0,
          reverseHoloSell: 2.5,
          reverseHoloLow: 0.29,
          reverseHoloTrend: 2.63,
          lowPriceExPlus: 1.2,
          avg1: 0.75,
          avg7: 2.81,
          avg30: 1.98,
          reverseHoloAvg1: 1.25,
          reverseHoloAvg7: 3.4,
          reverseHoloAvg30: 2.73,
        },
      },
    },
    {
      id: "det1-1",
      name: "Bulbasaur",
      supertype: "Pokémon",
      subtypes: ["Basic"],
      hp: "60",
      types: ["Grass"],
      evolvesTo: ["Ivysaur"],
      attacks: [
        {
          name: "Find a Friend",
          cost: ["Grass"],
          convertedEnergyCost: 1,
          damage: "",
          text: "Search your deck for a Grass Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless"],
      convertedRetreatCost: 1,
      set: {
        id: "det1",
        name: "Detective Pikachu",
        series: "Sun & Moon",
        printedTotal: 18,
        total: 18,
        legalities: {
          unlimited: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "DET",
        releaseDate: "2019/04/05",
        updatedAt: "2021/09/01 05:37:00",
        images: {
          symbol: "https://images.pokemontcg.io/det1/symbol.png",
          logo: "https://images.pokemontcg.io/det1/logo.png",
        },
      },
      number: "1",
      artist: "MPC Film",
      rarity: "Common",
      flavorText:
        "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.",
      nationalPokedexNumbers: [1],
      legalities: {
        unlimited: "Legal",
        expanded: "Legal",
      },
      images: {
        small: "https://images.pokemontcg.io/det1/1.png",
        large: "https://images.pokemontcg.io/det1/1_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/det1-1",
        updatedAt: "2025/08/06",
        prices: {
          holofoil: {
            low: 0.12,
            mid: 0.5,
            high: 5.03,
            market: 0.55,
            directLow: 0.2,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/det1-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 0.82,
          lowPrice: 0.02,
          trendPrice: 0.02,
          germanProLow: 0.0,
          suggestedPrice: 0.0,
          reverseHoloSell: 0.63,
          reverseHoloLow: 0.07,
          reverseHoloTrend: 0.49,
          lowPriceExPlus: 0.05,
          avg1: 0.55,
          avg7: 0.39,
          avg30: 0.7,
          reverseHoloAvg1: 0.5,
          reverseHoloAvg7: 0.6,
          reverseHoloAvg30: 0.49,
        },
      },
    },
    {
      id: "dv1-1",
      name: "Dratini",
      supertype: "Pokémon",
      subtypes: ["Basic"],
      hp: "40",
      types: ["Dragon"],
      evolvesTo: ["Dragonair"],
      attacks: [
        {
          name: "Wrap",
          cost: ["Grass", "Lightning"],
          convertedEnergyCost: 2,
          damage: "20",
          text: "Flip a coin. If heads, the Defending Pokémon is now Paralyzed.",
        },
      ],
      weaknesses: [
        {
          type: "Dragon",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless"],
      convertedRetreatCost: 1,
      set: {
        id: "dv1",
        name: "Dragon Vault",
        series: "Black & White",
        printedTotal: 20,
        total: 21,
        legalities: {
          unlimited: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "DRV",
        releaseDate: "2012/10/05",
        updatedAt: "2019/01/28 16:44:00",
        images: {
          symbol: "https://images.pokemontcg.io/dv1/symbol.png",
          logo: "https://images.pokemontcg.io/dv1/logo.png",
        },
      },
      number: "1",
      artist: "Masakazu Fukuda",
      rarity: "Rare Holo",
      flavorText:
        'It is called the "Mirage Pokémon" because so few have seen it. Its shed skin has been found.',
      nationalPokedexNumbers: [147],
      legalities: {
        unlimited: "Legal",
        expanded: "Legal",
      },
      images: {
        small: "https://images.pokemontcg.io/dv1/1.png",
        large: "https://images.pokemontcg.io/dv1/1_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/dv1-1",
        updatedAt: "2025/08/06",
        prices: {
          holofoil: {
            low: 0.73,
            mid: 1.99,
            high: 89.0,
            market: 2.12,
            directLow: 2.05,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/dv1-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 1.47,
          lowPrice: 0.15,
          trendPrice: 2.16,
          germanProLow: 0.0,
          suggestedPrice: 0.0,
          reverseHoloSell: 0.48,
          reverseHoloLow: 0.4,
          reverseHoloTrend: 1.95,
          lowPriceExPlus: 0.94,
          avg1: 0.94,
          avg7: 1.73,
          avg30: 2.14,
          reverseHoloAvg1: 0.48,
          reverseHoloAvg7: 2.49,
          reverseHoloAvg30: 1.72,
        },
      },
    },
    {
      id: "mcd19-1",
      name: "Caterpie",
      supertype: "Pokémon",
      subtypes: ["Basic"],
      hp: "50",
      types: ["Grass"],
      evolvesTo: ["Metapod"],
      attacks: [
        {
          cost: ["Grass"],
          name: "Surprise Attack",
          text: "Flip a coin. If tails, this attack does nothing.",
          damage: "20",
          convertedEnergyCost: 1,
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless"],
      convertedRetreatCost: 1,
      set: {
        id: "mcd19",
        name: "McDonald's Collection 2019",
        series: "Other",
        printedTotal: 12,
        total: 12,
        legalities: {
          unlimited: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "MCD19",
        releaseDate: "2019/10/15",
        updatedAt: "2022/10/10 15:12:00",
        images: {
          symbol: "https://images.pokemontcg.io/mcd19/symbol.png",
          logo: "https://images.pokemontcg.io/mcd19/logo.png",
        },
      },
      number: "1",
      artist: "Sekio",
      rarity: "Common",
      flavorText:
        "When attacked by bird Pokémon, it resists by releasing a terrifically strong odor from its antennae, but it often becomes their prey.",
      nationalPokedexNumbers: [10],
      legalities: {
        unlimited: "Legal",
        expanded: "Legal",
      },
      images: {
        small: "https://images.pokemontcg.io/mcd19/1.png",
        large: "https://images.pokemontcg.io/mcd19/1_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/mcd19-1",
        updatedAt: "2025/08/06",
        prices: {
          holofoil: {
            low: 2.1,
            mid: 8.17,
            high: 16.09,
            market: 10.29,
            directLow: null,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/mcd19-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 1.35,
          lowPrice: 0.5,
          trendPrice: 1.91,
          germanProLow: 0.0,
          suggestedPrice: 0.0,
          reverseHoloSell: 0.0,
          reverseHoloLow: 0.0,
          reverseHoloTrend: 1.71,
          lowPriceExPlus: 1.5,
          avg1: 4.0,
          avg7: 1.71,
          avg30: 1.58,
          reverseHoloAvg1: 0.5,
          reverseHoloAvg7: 1.71,
          reverseHoloAvg30: 1.37,
        },
      },
    },
  ],
  page: 1,
  pageSize: 20,
  count: 7,
  totalCount: 7,
};

// Mock data for sets
export const mockSets = {
  data: [
    {
      id: "base1",
      name: "Base",
      series: "Base",
      printedTotal: 102,
      total: 102,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "BS",
      releaseDate: "1999/01/09",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/base1/symbol.png",
        logo: "https://images.pokemontcg.io/base1/logo.png",
      },
    },
    {
      id: "base2",
      name: "Jungle",
      series: "Base",
      printedTotal: 64,
      total: 64,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "JU",
      releaseDate: "1999/06/16",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/base2/symbol.png",
        logo: "https://images.pokemontcg.io/base2/logo.png",
      },
    },
    {
      id: "base3",
      name: "Fossil",
      series: "Base",
      printedTotal: 62,
      total: 62,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "FO",
      releaseDate: "1999/10/10",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/base3/symbol.png",
        logo: "https://images.pokemontcg.io/base3/logo.png",
      },
    },
    {
      id: "base4",
      name: "Base Set 2",
      series: "Base",
      printedTotal: 130,
      total: 130,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "B2",
      releaseDate: "2000/02/24",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/base4/symbol.png",
        logo: "https://images.pokemontcg.io/base4/logo.png",
      },
    },
    {
      id: "base5",
      name: "Team Rocket",
      series: "Base",
      printedTotal: 83,
      total: 83,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "TR",
      releaseDate: "2000/04/24",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/base5/symbol.png",
        logo: "https://images.pokemontcg.io/base5/logo.png",
      },
    },
    {
      id: "gym1",
      name: "Gym Heroes",
      series: "Gym",
      printedTotal: 132,
      total: 132,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "G1",
      releaseDate: "2000/08/14",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/gym1/symbol.png",
        logo: "https://images.pokemontcg.io/gym1/logo.png",
      },
    },
    {
      id: "gym2",
      name: "Gym Challenge",
      series: "Gym",
      printedTotal: 132,
      total: 132,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "G2",
      releaseDate: "2000/10/16",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/gym2/symbol.png",
        logo: "https://images.pokemontcg.io/gym2/logo.png",
      },
    },
    {
      id: "neo1",
      name: "Neo Genesis",
      series: "Neo",
      printedTotal: 111,
      total: 111,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "NG",
      releaseDate: "2000/12/16",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/neo1/symbol.png",
        logo: "https://images.pokemontcg.io/neo1/logo.png",
      },
    },
    {
      id: "neo2",
      name: "Neo Discovery",
      series: "Neo",
      printedTotal: 75,
      total: 75,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "N1",
      releaseDate: "2001/06/01",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/neo2/symbol.png",
        logo: "https://images.pokemontcg.io/neo2/logo.png",
      },
    },
    {
      id: "neo3",
      name: "Neo Revelation",
      series: "Neo",
      printedTotal: 66,
      total: 66,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "N2",
      releaseDate: "2001/09/21",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/neo3/symbol.png",
        logo: "https://images.pokemontcg.io/neo3/logo.png",
      },
    },
    {
      id: "neo4",
      name: "Neo Destiny",
      series: "Neo",
      printedTotal: 113,
      total: 113,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "N3",
      releaseDate: "2002/02/28",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/neo4/symbol.png",
        logo: "https://images.pokemontcg.io/neo4/logo.png",
      },
    },
    {
      id: "ecard1",
      name: "Expedition Base Set",
      series: "E-Card",
      printedTotal: 165,
      total: 165,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "EX",
      releaseDate: "2002/09/15",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ecard1/symbol.png",
        logo: "https://images.pokemontcg.io/ecard1/logo.png",
      },
    },
    {
      id: "ecard2",
      name: "Aquapolis",
      series: "E-Card",
      printedTotal: 186,
      total: 186,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "AQ",
      releaseDate: "2003/01/15",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ecard2/symbol.png",
        logo: "https://images.pokemontcg.io/ecard2/logo.png",
      },
    },
    {
      id: "ecard3",
      name: "Skyridge",
      series: "E-Card",
      printedTotal: 182,
      total: 182,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "SK",
      releaseDate: "2003/05/12",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ecard3/symbol.png",
        logo: "https://images.pokemontcg.io/ecard3/logo.png",
      },
    },
    {
      id: "ex1",
      name: "Ruby & Sapphire",
      series: "EX",
      printedTotal: 109,
      total: 109,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "RS",
      releaseDate: "2003/06/18",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex1/symbol.png",
        logo: "https://images.pokemontcg.io/ex1/logo.png",
      },
    },
    {
      id: "ex2",
      name: "Sandstorm",
      series: "EX",
      printedTotal: 100,
      total: 100,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "SS",
      releaseDate: "2003/09/18",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex2/symbol.png",
        logo: "https://images.pokemontcg.io/ex2/logo.png",
      },
    },
    {
      id: "ex3",
      name: "Dragon",
      series: "EX",
      printedTotal: 97,
      total: 97,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "DR",
      releaseDate: "2003/11/24",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex3/symbol.png",
        logo: "https://images.pokemontcg.io/ex3/logo.png",
      },
    },
    {
      id: "ex4",
      name: "Team Magma vs Team Aqua",
      series: "EX",
      printedTotal: 95,
      total: 95,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "MA",
      releaseDate: "2004/03/15",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex4/symbol.png",
        logo: "https://images.pokemontcg.io/ex4/logo.png",
      },
    },
    {
      id: "ex5",
      name: "Hidden Legends",
      series: "EX",
      printedTotal: 101,
      total: 101,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "HL",
      releaseDate: "2004/06/01",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex5/symbol.png",
        logo: "https://images.pokemontcg.io/ex5/logo.png",
      },
    },
    {
      id: "ex6",
      name: "FireRed & LeafGreen",
      series: "EX",
      printedTotal: 112,
      total: 112,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "RG",
      releaseDate: "2004/08/30",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex6/symbol.png",
        logo: "https://images.pokemontcg.io/ex6/logo.png",
      },
    },
    {
      id: "ex7",
      name: "Team Rocket Returns",
      series: "EX",
      printedTotal: 109,
      total: 109,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "TRR",
      releaseDate: "2004/11/08",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex7/symbol.png",
        logo: "https://images.pokemontcg.io/ex7/logo.png",
      },
    },
    {
      id: "ex8",
      name: "Deoxys",
      series: "EX",
      printedTotal: 107,
      total: 107,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "DX",
      releaseDate: "2005/02/14",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex8/symbol.png",
        logo: "https://images.pokemontcg.io/ex8/logo.png",
      },
    },
    {
      id: "ex9",
      name: "Emerald",
      series: "EX",
      printedTotal: 106,
      total: 106,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "EM",
      releaseDate: "2005/05/09",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex9/symbol.png",
        logo: "https://images.pokemontcg.io/ex9/logo.png",
      },
    },
    {
      id: "ex10",
      name: "Unseen Forces",
      series: "EX",
      printedTotal: 115,
      total: 115,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "UF",
      releaseDate: "2005/08/22",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex10/symbol.png",
        logo: "https://images.pokemontcg.io/ex10/logo.png",
      },
    },
    {
      id: "ex11",
      name: "Delta Species",
      series: "EX",
      printedTotal: 113,
      total: 113,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "DS",
      releaseDate: "2005/10/31",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex11/symbol.png",
        logo: "https://images.pokemontcg.io/ex11/logo.png",
      },
    },
    {
      id: "ex12",
      name: "Legend Maker",
      series: "EX",
      printedTotal: 92,
      total: 92,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "LM",
      releaseDate: "2006/02/13",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex12/symbol.png",
        logo: "https://images.pokemontcg.io/ex12/logo.png",
      },
    },
    {
      id: "ex13",
      name: "Holon Phantoms",
      series: "EX",
      printedTotal: 110,
      total: 110,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "HP",
      releaseDate: "2006/05/03",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex13/symbol.png",
        logo: "https://images.pokemontcg.io/ex13/logo.png",
      },
    },
    {
      id: "ex14",
      name: "Crystal Guardians",
      series: "EX",
      printedTotal: 100,
      total: 100,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "CG",
      releaseDate: "2006/08/30",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex14/symbol.png",
        logo: "https://images.pokemontcg.io/ex14/logo.png",
      },
    },
    {
      id: "ex15",
      name: "Dragon Frontiers",
      series: "EX",
      printedTotal: 101,
      total: 101,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "DF",
      releaseDate: "2006/11/08",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex15/symbol.png",
        logo: "https://images.pokemontcg.io/ex15/logo.png",
      },
    },
    {
      id: "ex16",
      name: "Power Keepers",
      series: "EX",
      printedTotal: 108,
      total: 108,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "PK",
      releaseDate: "2007/02/14",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/ex16/symbol.png",
        logo: "https://images.pokemontcg.io/ex16/logo.png",
      },
    },
    {
      id: "dp1",
      name: "Diamond & Pearl",
      series: "Diamond & Pearl",
      printedTotal: 130,
      total: 130,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "DP",
      releaseDate: "2007/05/01",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/dp1/symbol.png",
        logo: "https://images.pokemontcg.io/dp1/logo.png",
      },
    },
    {
      id: "dp2",
      name: "Mysterious Treasures",
      series: "Diamond & Pearl",
      printedTotal: 123,
      total: 123,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "MT",
      releaseDate: "2007/08/22",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/dp2/symbol.png",
        logo: "https://images.pokemontcg.io/dp2/logo.png",
      },
    },
    {
      id: "dp3",
      name: "Secret Wonders",
      series: "Diamond & Pearl",
      printedTotal: 132,
      total: 132,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "SW",
      releaseDate: "2007/11/07",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/dp3/symbol.png",
        logo: "https://images.pokemontcg.io/dp3/logo.png",
      },
    },
    {
      id: "dp4",
      name: "Great Encounters",
      series: "Diamond & Pearl",
      printedTotal: 106,
      total: 106,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "GE",
      releaseDate: "2008/02/13",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/dp4/symbol.png",
        logo: "https://images.pokemontcg.io/dp4/logo.png",
      },
    },
    {
      id: "dp5",
      name: "Majestic Dawn",
      series: "Diamond & Pearl",
      printedTotal: 100,
      total: 100,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "MD",
      releaseDate: "2008/06/01",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/dp5/symbol.png",
        logo: "https://images.pokemontcg.io/dp5/logo.png",
      },
    },
    {
      id: "dp6",
      name: "Legends Awakened",
      series: "Diamond & Pearl",
      printedTotal: 146,
      total: 146,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "LA",
      releaseDate: "2008/08/20",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/dp6/symbol.png",
        logo: "https://images.pokemontcg.io/dp6/logo.png",
      },
    },
    {
      id: "dp7",
      name: "Stormfront",
      series: "Diamond & Pearl",
      printedTotal: 100,
      total: 100,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "SF",
      releaseDate: "2008/11/05",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/dp7/symbol.png",
        logo: "https://images.pokemontcg.io/dp7/logo.png",
      },
    },
    {
      id: "pl1",
      name: "Platinum",
      series: "Platinum",
      printedTotal: 127,
      total: 127,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "PL",
      releaseDate: "2009/02/11",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/pl1/symbol.png",
        logo: "https://images.pokemontcg.io/pl1/logo.png",
      },
    },
    {
      id: "pl2",
      name: "Rising Rivals",
      series: "Platinum",
      printedTotal: 111,
      total: 111,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "RR",
      releaseDate: "2009/05/16",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/pl2/symbol.png",
        logo: "https://images.pokemontcg.io/pl2/logo.png",
      },
    },
    {
      id: "pl3",
      name: "Supreme Victors",
      series: "Platinum",
      printedTotal: 147,
      total: 147,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "SV",
      releaseDate: "2009/08/19",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/pl3/symbol.png",
        logo: "https://images.pokemontcg.io/pl3/logo.png",
      },
    },
    {
      id: "pl4",
      name: "Arceus",
      series: "Platinum",
      printedTotal: 111,
      total: 111,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "AR",
      releaseDate: "2009/11/04",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/pl4/symbol.png",
        logo: "https://images.pokemontcg.io/pl4/logo.png",
      },
    },
    {
      id: "hgss1",
      name: "HeartGold & SoulSilver",
      series: "HeartGold & SoulSilver",
      printedTotal: 123,
      total: 123,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "HS",
      releaseDate: "2010/02/10",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/hgss1/symbol.png",
        logo: "https://images.pokemontcg.io/hgss1/logo.png",
      },
    },
    {
      id: "hgss2",
      name: "HS—Unleashed",
      series: "HeartGold & SoulSilver",
      printedTotal: 95,
      total: 95,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "UL",
      releaseDate: "2010/05/12",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/hgss2/symbol.png",
        logo: "https://images.pokemontcg.io/hgss2/logo.png",
      },
    },
    {
      id: "hgss3",
      name: "HS—Undaunted",
      series: "HeartGold & SoulSilver",
      printedTotal: 90,
      total: 90,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "UD",
      releaseDate: "2010/08/18",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/hgss3/symbol.png",
        logo: "https://images.pokemontcg.io/hgss3/logo.png",
      },
    },
    {
      id: "hgss4",
      name: "HS—Triumphant",
      series: "HeartGold & SoulSilver",
      printedTotal: 102,
      total: 103,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "TM",
      releaseDate: "2010/11/03",
      updatedAt: "2018/03/04 10:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/hgss4/symbol.png",
        logo: "https://images.pokemontcg.io/hgss4/logo.png",
      },
    },
    {
      id: "col1",
      name: "Call of Legends",
      series: "HeartGold & SoulSilver",
      printedTotal: 95,
      total: 95,
      legalities: {
        unlimited: "Legal",
      },
      ptcgoCode: "CL",
      releaseDate: "2011/02/09",
      updatedAt: "2020/08/14 09:35:00",
      images: {
        symbol: "https://images.pokemontcg.io/col1/symbol.png",
        logo: "https://images.pokemontcg.io/col1/logo.png",
      },
    },
  ],
};

// Mock data for types
export const mockTypes = {
  data: [
    "Colorless",
    "Darkness",
    "Dragon",
    "Fairy",
    "Fighting",
    "Fire",
    "Grass",
    "Lightning",
    "Metal",
    "Psychic",
    "Water",
  ],
};

// Mock data for rarities
export const mockRarities = {
  data: [
    "ACE SPEC Rare",
    "Amazing Rare",
    "Black White Rare",
    "Classic Collection",
    "Common",
    "Double Rare",
    "Hyper Rare",
    "Illustration Rare",
    "LEGEND",
    "Promo",
    "Radiant Rare",
    "Rare",
    "Rare ACE",
    "Rare BREAK",
    "Rare Holo",
    "Rare Holo EX",
    "Rare Holo GX",
    "Rare Holo LV.X",
    "Rare Holo Star",
    "Rare Holo V",
    "Rare Holo VMAX",
    "Rare Holo VSTAR",
    "Rare Prime",
    "Rare Prism Star",
    "Rare Rainbow",
    "Rare Secret",
    "Rare Shining",
    "Rare Shiny",
    "Rare Shiny GX",
    "Rare Ultra",
    "Shiny Rare",
    "Shiny Ultra Rare",
    "Special Illustration Rare",
    "Trainer Gallery Rare Holo",
    "Ultra Rare",
    "Uncommon",
  ],
};
