import type { PokemonApiResponse } from "../types/pokemon";

export const mockPokemonCards: PokemonApiResponse = {
  data: [
    {
      id: "hgss4-1",
      name: "Aggron",
      hp: "140",
      types: ["Metal"],
      rarity: "Rare Holo",
      set: {
        id: "hgss4",
        name: "HS—Triumphant",
        series: "HeartGold & SoulSilver",
        total: 102,
      },
      number: "1",
      artist: "Kagemaru Himeno",
      images: {
        small: "https://images.pokemontcg.io/hgss4/1.png",
        large: "https://images.pokemontcg.io/hgss4/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/hgss4-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 2.12,
          lowPrice: 0.3,
          trendPrice: 3.87,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "xy5-1",
      name: "Weedle",
      hp: "50",
      types: ["Grass"],
      rarity: "Common",
      set: {
        id: "xy5",
        name: "XY—Primal Clash",
        series: "XY",
        total: 160,
      },
      number: "1",
      artist: "Kouki Saitou",
      images: {
        small: "https://images.pokemontcg.io/xy5/1.png",
        large: "https://images.pokemontcg.io/xy5/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/xy5-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 0.15,
          lowPrice: 0.05,
          trendPrice: 0.12,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh1-1",
      name: "Caterpie",
      hp: "50",
      types: ["Grass"],
      rarity: "Common",
      set: {
        id: "swsh1",
        name: "Sword & Shield",
        series: "Sword & Shield",
        total: 202,
      },
      number: "1",
      artist: "Saya Tsuruta",
      images: {
        small: "https://images.pokemontcg.io/swsh1/1.png",
        large: "https://images.pokemontcg.io/swsh1/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh1-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 0.08,
          lowPrice: 0.02,
          trendPrice: 0.06,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh2-1",
      name: "Pikachu",
      hp: "60",
      types: ["Lightning"],
      rarity: "Common",
      set: {
        id: "swsh2",
        name: "Rebel Clash",
        series: "Sword & Shield",
        total: 192,
      },
      number: "1",
      artist: "Naoki Saito",
      images: {
        small: "https://images.pokemontcg.io/swsh2/1.png",
        large: "https://images.pokemontcg.io/swsh2/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh2-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 0.12,
          lowPrice: 0.03,
          trendPrice: 0.09,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh3-1",
      name: "Charizard",
      hp: "120",
      types: ["Fire"],
      rarity: "Rare Holo",
      set: {
        id: "swsh3",
        name: "Darkness Ablaze",
        series: "Sword & Shield",
        total: 189,
      },
      number: "1",
      artist: "PLANETA",
      images: {
        small: "https://images.pokemontcg.io/swsh3/1.png",
        large: "https://images.pokemontcg.io/swsh3/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh3-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 15.5,
          lowPrice: 8.99,
          trendPrice: 12.75,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh4-1",
      name: "Blastoise",
      hp: "130",
      types: ["Water"],
      rarity: "Rare Holo",
      set: {
        id: "swsh4",
        name: "Vivid Voltage",
        series: "Sword & Shield",
        total: 185,
      },
      number: "1",
      artist: "Kouki Saitou",
      images: {
        small: "https://images.pokemontcg.io/swsh4/1.png",
        large: "https://images.pokemontcg.io/swsh4/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh4-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 8.25,
          lowPrice: 4.5,
          trendPrice: 6.8,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh5-1",
      name: "Venusaur",
      hp: "130",
      types: ["Grass"],
      rarity: "Rare Holo",
      set: {
        id: "swsh5",
        name: "Battle Styles",
        series: "Sword & Shield",
        total: 163,
      },
      number: "1",
      artist: "Akira Komayama",
      images: {
        small: "https://images.pokemontcg.io/swsh5/1.png",
        large: "https://images.pokemontcg.io/swsh5/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh5-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 6.75,
          lowPrice: 3.25,
          trendPrice: 5.2,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh6-1",
      name: "Mewtwo",
      hp: "110",
      types: ["Psychic"],
      rarity: "Rare Holo",
      set: {
        id: "swsh6",
        name: "Chilling Reign",
        series: "Sword & Shield",
        total: 198,
      },
      number: "1",
      artist: "5ban Graphics",
      images: {
        small: "https://images.pokemontcg.io/swsh6/1.png",
        large: "https://images.pokemontcg.io/swsh6/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh6-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 12.3,
          lowPrice: 7.5,
          trendPrice: 9.8,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh7-1",
      name: "Lugia",
      hp: "130",
      types: ["Colorless"],
      rarity: "Rare Holo",
      set: {
        id: "swsh7",
        name: "Evolving Skies",
        series: "Sword & Shield",
        total: 203,
      },
      number: "1",
      artist: "Akira Komayama",
      images: {
        small: "https://images.pokemontcg.io/swsh7/1.png",
        large: "https://images.pokemontcg.io/swsh7/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh7-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 18.9,
          lowPrice: 12.0,
          trendPrice: 15.6,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh8-1",
      name: "Rayquaza",
      hp: "120",
      types: ["Dragon"],
      rarity: "Rare Holo",
      set: {
        id: "swsh8",
        name: "Fusion Strike",
        series: "Sword & Shield",
        total: 264,
      },
      number: "1",
      artist: "PLANETA",
      images: {
        small: "https://images.pokemontcg.io/swsh8/1.png",
        large: "https://images.pokemontcg.io/swsh8/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh8-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 22.45,
          lowPrice: 15.75,
          trendPrice: 19.2,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh9-1",
      name: "Gengar",
      hp: "110",
      types: ["Psychic"],
      rarity: "Rare Holo",
      set: {
        id: "swsh9",
        name: "Brilliant Stars",
        series: "Sword & Shield",
        total: 172,
      },
      number: "1",
      artist: "Kouki Saitou",
      images: {
        small: "https://images.pokemontcg.io/swsh9/1.png",
        large: "https://images.pokemontcg.io/swsh9/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh9-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 9.8,
          lowPrice: 6.25,
          trendPrice: 8.1,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh10-1",
      name: "Dragonite",
      hp: "130",
      types: ["Dragon"],
      rarity: "Rare Holo",
      set: {
        id: "swsh10",
        name: "Astral Radiance",
        series: "Sword & Shield",
        total: 189,
      },
      number: "1",
      artist: "Akira Komayama",
      images: {
        small: "https://images.pokemontcg.io/swsh10/1.png",
        large: "https://images.pokemontcg.io/swsh10/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh10-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 11.2,
          lowPrice: 7.8,
          trendPrice: 9.5,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh11-1",
      name: "Tyranitar",
      hp: "140",
      types: ["Darkness"],
      rarity: "Rare Holo",
      set: {
        id: "swsh11",
        name: "Lost Origin",
        series: "Sword & Shield",
        total: 196,
      },
      number: "1",
      artist: "PLANETA",
      images: {
        small: "https://images.pokemontcg.io/swsh11/1.png",
        large: "https://images.pokemontcg.io/swsh11/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh11-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 14.6,
          lowPrice: 9.9,
          trendPrice: 12.3,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh12-1",
      name: "Garchomp",
      hp: "130",
      types: ["Fighting"],
      rarity: "Rare Holo",
      set: {
        id: "swsh12",
        name: "Silver Tempest",
        series: "Sword & Shield",
        total: 245,
      },
      number: "1",
      artist: "Kouki Saitou",
      images: {
        small: "https://images.pokemontcg.io/swsh12/1.png",
        large: "https://images.pokemontcg.io/swsh12/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh12-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 13.4,
          lowPrice: 8.75,
          trendPrice: 11.2,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "swsh12pt5-1",
      name: "Lucario",
      hp: "110",
      types: ["Fighting"],
      rarity: "Rare Holo",
      set: {
        id: "swsh12pt5",
        name: "Crown Zenith",
        series: "Sword & Shield",
        total: 159,
      },
      number: "1",
      artist: "Akira Komayama",
      images: {
        small: "https://images.pokemontcg.io/swsh12pt5/1.png",
        large: "https://images.pokemontcg.io/swsh12pt5/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/swsh12pt5-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 16.8,
          lowPrice: 11.25,
          trendPrice: 14.1,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "sv1-1",
      name: "Koraidon",
      hp: "130",
      types: ["Fighting"],
      rarity: "Rare Holo",
      set: {
        id: "sv1",
        name: "Scarlet & Violet",
        series: "Scarlet & Violet",
        total: 198,
      },
      number: "1",
      artist: "PLANETA",
      images: {
        small: "https://images.pokemontcg.io/sv1/1.png",
        large: "https://images.pokemontcg.io/sv1/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv1-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 25.3,
          lowPrice: 18.5,
          trendPrice: 22.1,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "sv2-1",
      name: "Miraidon",
      hp: "130",
      types: ["Lightning"],
      rarity: "Rare Holo",
      set: {
        id: "sv2",
        name: "Paldea Evolved",
        series: "Scarlet & Violet",
        total: 193,
      },
      number: "1",
      artist: "Kouki Saitou",
      images: {
        small: "https://images.pokemontcg.io/sv2/1.png",
        large: "https://images.pokemontcg.io/sv2/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv2-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 28.9,
          lowPrice: 21.75,
          trendPrice: 25.6,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "sv3-1",
      name: "Ogerpon",
      hp: "120",
      types: ["Grass"],
      rarity: "Rare Holo",
      set: {
        id: "sv3",
        name: "Obsidian Flames",
        series: "Scarlet & Violet",
        total: 197,
      },
      number: "1",
      artist: "Akira Komayama",
      images: {
        small: "https://images.pokemontcg.io/sv3/1.png",
        large: "https://images.pokemontcg.io/sv3/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv3-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 32.15,
          lowPrice: 24.8,
          trendPrice: 28.9,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "sv4-1",
      name: "Iron Valiant",
      hp: "110",
      types: ["Psychic"],
      rarity: "Rare Holo",
      set: {
        id: "sv4",
        name: "Paradox Rift",
        series: "Scarlet & Violet",
        total: 182,
      },
      number: "1",
      artist: "PLANETA",
      images: {
        small: "https://images.pokemontcg.io/sv4/1.png",
        large: "https://images.pokemontcg.io/sv4/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv4-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 19.75,
          lowPrice: 14.2,
          trendPrice: 17.3,
          suggestedPrice: 0.0,
        },
      },
    },
    {
      id: "sv5-1",
      name: "Gouging Fire",
      hp: "130",
      types: ["Fire"],
      rarity: "Rare Holo",
      set: {
        id: "sv5",
        name: "Temporal Forces",
        series: "Scarlet & Violet",
        total: 162,
      },
      number: "1",
      artist: "Kouki Saitou",
      images: {
        small: "https://images.pokemontcg.io/sv5/1.png",
        large: "https://images.pokemontcg.io/sv5/1_hires.png",
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv5-1",
        updatedAt: "2025/08/06",
        prices: {
          averageSellPrice: 35.6,
          lowPrice: 27.9,
          trendPrice: 31.8,
          suggestedPrice: 0.0,
        },
      },
    },
  ],
  page: 1,
  pageSize: 20,
  count: 20,
  totalCount: 20,
};

export const mockSets = {
  data: [
    { id: "hgss4", name: "HS—Triumphant", series: "HeartGold & SoulSilver" },
    { id: "xy5", name: "XY—Primal Clash", series: "XY" },
    { id: "swsh1", name: "Sword & Shield", series: "Sword & Shield" },
    { id: "swsh2", name: "Rebel Clash", series: "Sword & Shield" },
    { id: "swsh3", name: "Darkness Ablaze", series: "Sword & Shield" },
    { id: "swsh4", name: "Vivid Voltage", series: "Sword & Shield" },
    { id: "swsh5", name: "Battle Styles", series: "Sword & Shield" },
    { id: "swsh6", name: "Chilling Reign", series: "Sword & Shield" },
    { id: "swsh7", name: "Evolving Skies", series: "Sword & Shield" },
    { id: "swsh8", name: "Fusion Strike", series: "Sword & Shield" },
    { id: "swsh9", name: "Brilliant Stars", series: "Sword & Shield" },
    { id: "swsh10", name: "Astral Radiance", series: "Sword & Shield" },
    { id: "swsh11", name: "Lost Origin", series: "Sword & Shield" },
    { id: "swsh12", name: "Silver Tempest", series: "Sword & Shield" },
    { id: "swsh12pt5", name: "Crown Zenith", series: "Sword & Shield" },
    { id: "sv1", name: "Scarlet & Violet", series: "Scarlet & Violet" },
    { id: "sv2", name: "Paldea Evolved", series: "Scarlet & Violet" },
    { id: "sv3", name: "Obsidian Flames", series: "Scarlet & Violet" },
    { id: "sv4", name: "Paradox Rift", series: "Scarlet & Violet" },
    { id: "sv5", name: "Temporal Forces", series: "Scarlet & Violet" },
  ],
};

export const mockTypes = {
  data: [
    "Colorless",
    "Darkness",
    "Dragon",
    "Fighting",
    "Fire",
    "Grass",
    "Lightning",
    "Metal",
    "Psychic",
    "Water",
  ],
};

export const mockRarities = {
  data: [
    "Common",
    "Uncommon",
    "Rare",
    "Rare Holo",
    "Rare Ultra",
    "Secret Rare",
  ],
};
